### ISSUE TITLE
[Suggestion] Keyboard Shortcut

### ISSUE THREAD

**Issue by devajmeireles** [laravel/pail#1]
Hey, Nuno! Thanks for this awesome package.

I'd like to suggest a new feature: 
- Provide the ability to use a keyboard shortcut to restart the pail: `Cmd` or `Alt` + `P`, for example. Also, I think it'd be awesome to be able to change the keyboard shortcut as part of one `config/pail.php` file.

**Comment by jdecode** [comment]
By default the command does a `tail` - meaning that it continues to log the output as it receives - as a "listener"

What is expected to happen when we "restart" the command (since, technically, the command never "stopped", unless explicitly stopped)?

**Comment by nunomaduro** [comment]
I don't understand why we would want to "restart" the command in the first place.
