### ISSUE TITLE
Style [sf-dump] not found

### ISSUE THREAD

**Issue by Baspa** [laravel/pail#13]
### Laravel Package Version

v1.0.0-beta.2

### Laravel Version

10.23.1

### PHP Version

8.2

### Description

I'm running the `php artisan:pail` command. I accidentally added an "s" somewhere in my code which caused Pail to throw the following error: 

```
Style [sf-dump] not found.

  at vendor/nunomaduro/termwind/src/Exceptions/StyleNotFound.php:27
     23▕      * Creates a new style not found instance from the given style.
     24▕      */
     25▕     public static function fromStyle(string $style): self
     26▕     {
  ➜  27▕         return new self(sprintf('Style [%s] not found.', $style));
     28▕     }
     29▕ }
     30▕ 
```

### Steps To Reproduce

1. Run `php artisan:pail`

2. Call a route which leads to a controller method that contains a random character in it. For example:

```php
public function index(Request $request): array
{
    $data = [];
    s
    return $data;
}

**Comment by Baspa** [comment]
I could try to make a PR later this week.

**Comment by driesvints** [comment]
Seems you sent in that PR so let's see how it goes. Thanks!
