### ISSUE TITLE
displaying arrays

### ISSUE THREAD

**Issue by michabbb** [laravel/pail#18]
i assume the current state is wanted, but because it looks very strange to me, I just wanted to mention it:

this....
```php
Log::debug('test',['test' => 'test', 'test2' => 'test2','test3' => 'test3']);
```
produces this:

![image](https://github.com/laravel/pail/assets/3524595/2d8c4b20-1e34-4137-bb38-3ec5839d875e)

and I personally would expect an output where the array gets displayed like `dump(...)` does:

![image](https://github.com/laravel/pail/assets/3524595/fb3dc275-9da0-436e-8e28-5b9b50efff65)

so it´s readable for a human. ideas ?

**Comment by nunomaduro** [comment]
We will consider changing this if more people report it. Thanks!

**Comment by michabbb** [comment]
many years ago:

```
me: having dump() without knowing from which line it comes: total nonsense and stupid
everyone else: wuff wuff wuff.... nobody cares, it´s your problem using it more than once in your code
years later: hey, great news: dump() now shows the line of code where it comes from
everyone else: wow, great! amazing !!! party !!!
```

![image](https://github.com/laravel/pail/assets/3524595/ca01ee4b-8b22-4d50-b299-c0ff4af4364e)
