### ISSUE TITLE
start the output with displaying the last lines in the log

### ISSUE THREAD

**Issue by aptcreativedesign** [laravel/pail#19]
It would be useful if there was something similar to the [spatie/laravel-tail](https://github.com/spatie/laravel-tail#usage) packages `--lines=X` command option to start the tail with previous lines.

With the included ability to add either `-v` or `-vv` options as well

At the moment if you forget to start pail or have it running but forgot to add the verbosity level you have to recreate the error before you can see it in the logs.

**Comment by nunomaduro** [comment]
Thanks for the suggestion! That's not possible at the moment.
