### ISSUE TITLE
Configurable timeout

### ISSUE THREAD

**Issue by cyppe** [laravel/pail#26]
Would be nice to be able to set parameter for changing default timeout value when needed:

 INFO  Maximum execution time exceeded.

Currently it's hardcoded:

` Process::timeout(3600)`

Something like

`php artisan pail --timeout=10000`

or 

`php artisan pail --notimeout`

Would be nice.

Thanks for a awesome tool!

**Comment by crynobone** [comment]
Hi there, it would be best that you attempt the PR so we can see the code involved to make this happen. Thanks

**Comment by cyppe** [comment]
I opened PR but it was rejected. 

https://github.com/laravel/pail/pull/27

Please read my comment on it, about considering to just increase the hardcoded timeout to something bigger than 1 hour. That would not add any complexity.

**Comment by Heyian** [comment]
Sorry to necropost but if you're like me, you stumbled onto this post and you though that this is not implemented. But it was with PR #45. You can now use the --timeout option.
