### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by gjm** [laravel/pail#39]
### Laravel Package Version

1.1.3

### Laravel Version

10.48.19

### PHP Version

8.3.6

### Database Driver & Version

PostgreSQL 16.4

### Description

I have a custom `UserProvider` for my Laravel app that performs some logging internally.

Here's a simplified snippet of `retrieveById()` (this is not real code! it's just to convey the logic inside the method):

```php
public function retrieveById($identifier): ?Authenticatable
    {
        $user = User::find($identifier);
        if ($user) {
            $this->log->info('User retrieved from DB!');
        } else {
            $this->log->error('User not found!');
        }
        return $user;
    }
```

When Pail tries to log the _"User retrieved from DB!"_ message on the first access to the authenticated user it, in turn, tries to read the authenticated user which triggers another call to `retrieveById`, since the user instance in the session guard is not yet populated, and the loop goes on.

### Steps To Reproduce

Use a custom `UserProvider` as described above.

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by gjm** [comment]
I think I've made clear what the issue was. No question on a community support forum will solve my problem. 

Right now the issue is in Pail (or Laravel itself). The issue occurs because I trigger logging while loading the authenticated user which, in turn, tries loading the authenticated user which triggers logging... and so on.

The call stack is something like this (assuming `SessionGuard` is used):

1. call `Auth::id()`
2. call `SessionGuard::user()` 
3. call `UserProvider::retrieveById()` to get the user from database
4. `UserProvider` triggers logging
5. Pail logging handler calls `Auth::id()` to get the username
6. Goto 1

If you answer me that I shouldn't log in `UserProvider` I'll accept that answer, even though I don't agree with it, but right now I feel there is an issue. Maybe the issue is in Laravel's auth stack itself...

Will gladly provide any additional info if needed.

Thanks again.
