### ISSUE TITLE
Problem when installing fresh Laravel Application due to pail requirement to Install or enable PHP's pcntl extension. 

### ISSUE THREAD

**Issue by kmaphane** [laravel/pail#43]
### Laravel Package Version

1.6.1

### Laravel Version

11.9

### PHP Version

8.2

### Description

 I've been using Laravel Herd on my Windows PC, I'm encountering an error that requires the pcntl extension, which isn't available on Windows. This extension is needed for the laravel/pail package. as below 
 
 Problem 1
    - laravel/pail[v1.1.0, ..., v1.1.4] require ext-pcntl * -> it is missing from your system. Install or enable PHP's pcntl extension.
    - Root composer.json requires laravel/pail ^1.1 -> satisfiable by laravel/pail[v1.1.0, ..., v1.1.4].

### Steps To Reproduce

Create a new site using Herd. This will fail. Or you can run laravel new <project name> powershell. This will still fail. Not too sure what change in the last couple of weeks.

**Comment by rpsohag** [comment]
I'm also facing the same issue with Laravel Herd on Windows. Since the pcntl extension isn't supported on Windows, I worked around this by using `composer install --ignore-platform-req=ext-pcntl`. However, it would be great if there was a better way to handle this dependency for Windows users. **Any updates or solutions would be appreciated!**

**Comment by EjiErubani** [comment]
1. Install with ignoring **ext-pcntl** > `composer create-project laravel/laravel:^11.3.0 example-app --ignore-platform-req=ext-pcntl`
2. Delete `"laravel/pail": "^1.1",` from `composer.json`
3. Run `composer update`

**Comment by kmaphane** [comment]
Good day,

Thanks for the response. I have been able to install using other strategies, but I guess this just means I can never quickly spin up an application using Herd.

Regards,

Kenna
________________________________

**Comment by kmaphane** [comment]
Hi,

Thanks will do.

Regards,

Kenna
________________________________

**Comment by ChaosWebDev** [comment]
> install previous version for short term solution:
> 
> ```
> composer create-project laravel/laravel:^11.2.1 example-app
> ```

Is there a way for force `laravel new <app>` to use an older version until they fix it?

**Comment by taylorotwell** [comment]
Should be ok now on skeleton 11.3.1

**Comment by kmaphane** [comment]
Thanks a mill
________________________________

**Comment by rkgarcia** [comment]
The project creation doesn't have the issue, but the problem is present at application start
```
[logs]
[logs]    ERROR  Command "pail" is not defined. Did you mean one of these?
[logs]
[logs]   ⇂ sail:add
[logs]   ⇂ sail:install
[logs]   ⇂ sail:publish
[logs]
[logs] php artisan pail --timeout=0 exited with code 1
```
I fixit removing the pail invocation at composer.json
```\"php artisan pail --timeout=0\" ```
